matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      language: node_js
      node_js: '12'

    - os: linux
      language: node_js
      node_js: '12'
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libx11-dev
            - zlib1g-dev
            - libpng12-dev
            - libxtst-dev
            - g++-4.8
            - gcc-4.8

before_script:
  - | # Fix chrome-sandbox: https://github.com/electron/electron/issues/17972
      if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
        echo "Fixing chrome-sandbox permissions..."
        sudo chown root ./node_modules/electron/dist/chrome-sandbox
        sudo chmod 4755 ./node_modules/electron/dist/chrome-sandbox
      fi
script:
  - npm run dist
