matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      language: node_js
      node_js: '12'

    - os: linux
      dist: bionic
      sudo: true
      language: node_js
      node_js: '12'
      addons:
        apt:
          packages:
            - libx11-dev
            - zlib1g-dev
            - libpng-dev
            - libxtst-dev

before_script:
  - | # Disable sandbox: https://github.com/electron/electron/issues/17972
      if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
        patch -p1 -i patches/app-builder-lib+22.3.6.patch
      fi
script:
  - npm run dist
